const catalogData = [
  {
    id: "1",
    prioritate: "хит продаж",
    imgUrl: "https://i.ibb.co/n1q06D2/cat1.png",
    size: ["40", "42", "44", "46", "48"],
    name: "Платье",
    price: "5 000 ₽",
  },

  {
    id: "2",
    prioritate: "новинка",
    imgUrl: "https://i.ibb.co/16CsRKW/cat2.png",
    size: ["40", "42", "44", "46", "48"],
    name: "Спортивный костюм",
    price: "12 000 ₽",
  },
  {
    id: "3",
    prioritate: "последний размер",
    imgUrl: "https://i.ibb.co/QPSz4qQ/cat3.png",
    size: ["40", "42", "44", "46", "48"],
    name: "Рубашка",
    price: "4 000 ₽",
  },
  {
    id: "4",
    prioritate: "распродажа",
    imgUrl: "https://i.ibb.co/FYbGcg0/cat4.png",
    size: ["40", "42", "44", "46", "48"],
    name: "Рубашка",
    price: "4 500 ₽",
  },
  {
    id: "5",
    prioritate: "",
    imgUrl: "https://i.ibb.co/hXQrXJv/cat5.png",
    size: ["40", "42", "44", "46", "48"],
    name: "Платье",
    price: "8000 ₽",
  },
  {
    id: "6",
    prioritate: "распродажа",
    imgUrl: "https://i.ibb.co/XWqxywt/cat6.png",
    size: ["40", "42", "44", "46", "48"],
    name: "Домашний комплект",
    price: "4500 ₽",
  },
  {
    id: "7",
    prioritate: "",
    imgUrl: "https://i.ibb.co/vzPtnzj/cat7.png",
    size: ["40", "42", "44", "46", "48"],
    name: "Платье",
    price: "9000 ₽",
  },
  {
    id: "8",
    prioritate: "",
    imgUrl: "https://i.ibb.co/GJ8F8jW/cat8.png",
    size: ["40", "42", "44", "46", "48"],
    name: "Платье",
    price: "7000 ₽",
  },
  {
    id: "9",
    prioritate: "",
    imgUrl: "https://i.ibb.co/pZ1kC3V/cat9.png",
    size: ["40", "42", "44", "46", "48"],
    name: "Платье",
    price: "7000 ₽",
  },
];

export default catalogData;
